apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-ssdraid
  labels:
    argocd.argoproj.io/instance: openebs-extra    
allowVolumeExpansion: true
parameters:
  storage: lvm
  volgroup: lvmvg_ssdraid
provisioner: local.csi.openebs.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
