apiVersion: v2
name: keycloak
description: An umbrella chart for keycloak
type: application
version: 0.1.0
dependencies:
  - name: keycloak
    version: 18.x.x
    repository: "oci://registry-1.docker.io/bitnamicharts"
  - name: postgresql-ha
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.3.x