apiVersion: v2
name: pgo
description: "PostgreSQL Operator for Kubernetes"
type: application
version: 0.1.0
dependencies:
- name: pgo
  version: 5.x.x
  repository: oci://registry.arico-b2b.com/neorcloud
