apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: manage
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
    
  - name: read-only
    description: Read-only privileges to manage
    policies:
    - p, proj:manage:read-only, applications, get, manage/*, allow
    groups:
    - manage-readonly

  - name: admin
    description: admin privileges to manage
    policies:
    - p, proj:manage:admin, applications, *, manage/*, allow
    - p, proj:manage:admin, exec, create, manage/*, allow
    groups:
    - manage-admin
    - ArgoCdAdmins
