---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-keycloak
spec:
  parentRefs:
  {{- toYaml .Values.keycloak.httpRoute.parentRefs | nindent 6 }}
  hostnames:
  {{- toYaml .Values.keycloak.httpRoute.hostnames | nindent 6 }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - kind: Service
      name: {{ .Release.Name }}-headless
      port: 8200
