---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-postgresql-auth
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgCLHAOOXQFqXTz+ULfg8dkKE1C944Ki2mWAlKYJfN53OALAuxhK+RjfSCQ8IM7gI1sgVvHbNJ3Ac4MEYRXvgYFSPQ8Q6LdZSCFYn/XknY1PsUn0aKNlqPfyoYwDrpwEFqFra17A1SKGDqwrXSP4IAVqHog1BFP/npa090Ag6rmiP6VpSTY3ubF5SELUEkAJGjYp6O36Fd93SGVoCh+F7rzgT4RtBOINVx1rwVLomXfiSXy6027PsLW61L3MWM4sYNfCXZFHdlic65BklH4MIBxRWkhyvMvHpUIgKueTuVMHNWJ2ttNUEgnomOfLNfaApuEQ5VaSOWvHvAMvcGbj/RFKwDJjj8E4grOXWLA31M9q1Uqm0zBoyTVO8Q+7tKzM0njMwWY/BCQ/LyYyUB6hulRRVZI6Ck0JNb4BNc+sk66mKIN/uVvID5xIJEU26L8gOKWXbc/rjiieS79Xu6MOsVwe5SrHe5PvttXjiHPWXCvFjFI/pduZ6NMy3nQBZvcHgJ9HjH16aLxcdmHgWXokC3UC3W6pmHaq0rD7G6FqceNEYjD80sykieYa1mwMlAEiVvZlbesppJznfKSy85kGQskXoCCocWZgjDtOnFnScyCnCu+qeC2U24h34S1hy/9OFdPR2x1xJU4JPFX+o2f7w2Fyx7q2F9je/5WIv9dbi3kbVZmKkxcCHFIrjrhvBiKdQCD+ZlJ3Rjq9JmvUK1ozu2tuTSt4Hg==
    password: AgAYtoX83XyOPhS02jH/4ZE65qYWxylMd3wyYgu3Slo0IaMqoDtcSS2QaL+C19eW4kVUDAXO8c3xt8WtLTyYmrEwED5QpSGfZlCs7wy0/NV8+aTOOJILA9dPdqftjKmEhN29eHQ7y74jx3/TS7TIcvEda/f/pg0ryijzbJh5QeUDNY6bQ0MRgYQ1FOBVK+GO4ZxZz3qW2/GKxMKdt1TDZ2JD9MbI4Jm9n544U/5pNpHFYQhFrcmCJ+16j4zjQOUX2chm4IjsluGmEgBBWM/xo/+oAivlWkFUgmAtKyOZ/Mt5Vl+ADC8dGWkrycd3WMnoIfRmhBMI+MV26aYGFo+defAYWpqvaFXnhSUFBLLK5qaI/1FnktYGLGklwKfg3c6cUlKBwB8Ol/GeDfSQfjq2D629KxZfXtAinoVyHG9TnWOQprfQdVy90ELHeZWSefZZukkcRDrz8hUbpSmZgfqxq3wHV/zOyLMWRcVzwATVuirKkAjly5+lf3P4ijcTcpLgUC+4e8gUGK/K5s0vuLINoIBtXFt0FwKHEk2sHCTxik9q4WMqiNAPKCAgYcsnAmAF8Ef1J9Yu0xbipDRdSz/zS6G3IewvldHQ21NLwzIxc4cWEGGjUv21F1J3xAWcAVY96Gp+MaBd38jk6UH8NSC4BmpxjHF84P+PDU+k9bRYHghL4FPVU4G1Od3WuUDG0sTpb+6ARdau3EeCG2VL7YIedp0y9rOXXA==
    repmgr-password: AgAvkQFeJnpdXs1vGd64PXo27E91DoX/XOkpu9lY9cI9u7XEcV1bsvkUgh3DWuMsbdugTB1GLDzzQ4HSqkeQnwd9492+iYuBKDKv45jsgsK962s0/JG/rlVa6QBPxblW09yH19SN5PN5dN7HiHVAMLkU0vuO82oV4XsuGoykmyn0yfJ+2mbfdiwedfBSPbL+b6GgHEHV4QotmcaK6Q6hLdkgZWPo9vB/v6HuoR/6G+uqTj7WsyMkydc9sIK36Bhowm2Oeiy19WP9yahiMRZhimHfZyFPfn1JfGOMOBzYHYabVwxp1A00koHHq+ikdWnOrLr3NjH6bnQxAJnOia4KRujV5j2Tj6TUCTDOcRazjdPzKFvP1VrwWSGXR7T9zgCntnqcpYhlj/4KDAvUXK0lTakqq5pz/1bdFz1jlaY/E2bgbcts1CxzQovYywtbBkkD58h/FLg5Vx9fP2eje2CFlKkD0OMItuv8AvQY/2XtrDOk8HvT+OfDZf7ch5FTVWIBXoLQsZW6euO8Zodl7mhs8jcTkV4zGrvHkxFW2mi0+yltchrIewcxMZ/6gR1vkVPeLvhGbLYjP7ysG2CF/avC8PibL8KqeyYVrbmQIHVHKFEdgNHpJrQi/tzidO9WdhhGs0R4/SmdBJlT6KlUDRFlki1acaC4QjlTf8eEER9XDykySMMM3dnTSKSg2DNcMhgCuGuvYCeuVfoCkiG5OTIDmpjX98VghQ==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-postgresql-auth
      namespace: keycloak
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-admin-auth
  namespace: keycloak
spec:
  encryptedData:
    admin-password: AgBmhl5PpOpXF76K8PYFKmbCzZ1WODrvhLPyo7vjxQzQYtvbZby04GrnA0Wyso4GuF/Z/pX/hTdx+iGFJp4M1oGfaUHbomo+lkrOWCHxib1qIUFCh9m5ICu4z0Vzf8x9ODVfBPXLCue+AoshJG1ODTkjNqq47AHhDiJHnw0S/P+emmP83dvtz4XK1jvTSA1hHaN0D393cpMioS6nCFjcERL8AgPRVtGImffmSmKhG0tLgi60j2FRU66lVaa5lyyJlf6aFO+q+tVOZ8J8lheuC+jmF5box1ZRqgVXowoveHzT7J6ke0Rt09rjRZMivYIpU5Go3GQFzfxWc5YYiPmWWA6lj42FVrFbEDlFToCgrVsDXJJokxlNOFSFN9NHa8DJm92yZ3dz0KYHmKz7pR+RoIVpGq2GD46/BMCQMnqfpI4oJmkgWJT/hRDXpW90mpkGRiZspDDlS6bxKCFgjOblMytG0SM5Bw5x3SIjfHZ1SqRDD2F9nlQ/rEaZ270bxKppa2QhBQcXPXWnHQ+nZSBClQgu+sDGtU+DC3qGjx5iA/lAktH3YV2PfHg7Bonxo32dXI9TBRNklXjGcpR3oervd7cX/hsop5X9aczDW3oEscEydGihA+ejUDlTZU1fy9CvPp86gCRQdvviviFILztb2F/ntXoBgR+9lnvajxyf4bsteY+Kuo3cIigcsuUG1DcFYz+JiYJGbZGervxQXXuQucaDk0nRGw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-admin-auth
      namespace: keycloak