apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-140"
  name: velero
  namespace: argocd
 
spec:
  destination:
    namespace: velero
    server: {{ .Values.spec.destination.server }}
  project: {{ .Values.spec.destination.project }}
  syncPolicy:
   automated:
     prune: false
     selfHeal: false
   syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=orphan

  source:
    targetRevision: {{ .Values.spec.source.targetRevision }}
    chart: {{ .Values.spec.source.chart }}
    helm:
      values: |-
        # image:
        #    repository: repo.rovzane.com/dockerhub/velero/velero

        upgradeCRDs: false

        credentials:
          useSecret: true
          existingSecret: velero-arvan-secret
        
        configuration:
          backupStorageLocation:
            - name: "default"
              provider: aws
              bucket: backup-tools
              prefix: velero-tools
              config:
                region: simin
                s3ForcePathStyle: true
                publicUrl: https://s3.ir-thr-at1.arvanstorage.ir
                s3Url: https://s3.ir-thr-at1.arvanstorage.ir

        snapshotsEnabled: false
   
        schedules:
          #  clustertestbackuo:
          #    schedule: "0 */5 * * *"
          #    template:
          #      snapshotVolumes: false      
          #      ttl: "168h"
          #      includedNamespaces:
          #       - '*'

           gitlabbackuo:
             schedule: "every 6h"
             template:
               snapshotVolumes: false      
               ttl: "168h"
               includedNamespaces:
                - 'gitlab'

        initContainers: 
           - name: velero-plugin-for-aws
             image: velero/velero-plugin-for-aws:v1.8.2
             imagePullPolicy: IfNotPresent
             volumeMounts:
               - mountPath: /target
                 name: plugins
